### ISSUE TITLE
Recording issue with log PushConn: no usable tracks found

### ISSUE THREAD

**Issue by dwinurhadia** [deburau/galene-docker#1]
I've running galene-docker with latest version,
But when I type` /record` its getting alert` The Server said : Write to disk no usable tracks found`

Is there any dependency package or issue with docker-compose env?

Here is my docker-compose env
 ```
galene:
  image: deburau/galene
  environment:
    - GALENE_DATA=/data
    - GALENE_GROUPS=/groups
    - GALENE_RECORDINGS=/recordings
    - GALENE_TURN=localhost:1194
    - GALENE_HTTP=:80
    - GALENE_INSECURE=1
    - GALENE_MDNS
    - GALENE_MEMPROFILE=/profiles/mem.profile
    - GALENE_MUTEXPROFILE=/profiles/mutex.profile
    - GALENE_CPUPROFILE=/profiles/cpu.profile
    - GALENE_REDIRECT
    - GALENE_RELAY_ONLY
    - GALENE_STATIC
    - WAIT_LOGGER_LEVEL=info
    - WAIT_TIMEOUT=60
    - WAIT_AFTER=1
    - WAIT_SLEEP_INTERVAL=5
  volumes:
    - ./voldata:/data
    - ./volgroups:/groups
    - ./volrecordings:/recordings
    - ./profiles:/profiles
```

**Comment by deburau** [comment]
Just tried it on my own server and it works.

This is my docker-compose.yml:

```
version: '3'

services:
  galene:
    image: deburau/galene:0.5.5
#    image: galene:0.5.5
    container_name: galene
    restart: always
    volumes:
      - ./data:/data
      - ./groups:/groups
      - ./recordings:/recordings
      - ./profiles:/profiles
    networks:
      traefik:
    environment:
      - WAIT_HOSTS=a.b.c.d:5349
      - WAIT_LOGGER_LEVEL=info
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_AFTER_HOSTS=1
      - WAIT_SLEEP_INTERVAL=5
      - GALENE_CPUPROFILE=/profiles/cpu.profile
      - GALENE_DATA=/data
      - GALENE_GROUPS=/groups
      - GALENE_HTTP=:80
      - GALENE_INSECURE=1
      - GALENE_MDNS
      - GALENE_MEMPROFILE/profiles/mem.profile
      - GALENE_MUTEXPROFILE/profiles/mutex.profile
      - GALENE_RECORDINGS=/recordings
      - GALENE_REDIRECT
      - GALENE_RELAY_ONLY
      - GALENE_STATIC
      - GALENE_TURN=
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.galene.rule=Host(`galene.example.com`)"
      - "traefik.http.routers.galene.entrypoints=websecure"
      - "traefik.http.routers.galene.tls=true"
      - "traefik.http.routers.galene.tls.domains[0].main=galene.example.com"
      - "traefik.http.routers.galene.service=galene"
      - "traefik.http.services.galene.loadbalancer.server.port=80"
      - "traefik.http.services.galene.loadbalancer.server.scheme=http"
      - "traefik.http.services.galene.loadbalancer.passhostheader=true"

networks:
  traefik:
    external: true
```

If you are not using traefik you can ignore the trafik parts.
